services:
  - type: web
    name: saep-quizz-gameficado
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 3000
      - key: GEMINI_MODEL
        value: gemini-2.5-flash
